[workspace]
name = "ros2-steamdeck-turtlesim"
channels = ["conda-forge", "robostack-jazzy"]
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-ros-base = "*"
ros-jazzy-teleop = { path = "src/teleop/package.xml" }
pygame = "*"

[tasks]
sim = "ros2 run turtlesim turtlesim_node"
teleop = "ros2 run teleop teleop_node"
